import React from 'react'
import { useParams } from 'react-router-dom'
import { useAppContext } from '../App'
import { motion } from 'framer-motion'
import { FileText, Package, ExternalLink, Scale, ShieldCheck } from 'lucide-react'
import EscalationTracker from '../components/EscalationTracker'

const fadeUp = (delay = 0) => ({
  initial: { opacity: 0, y: 20 },
  animate: { opacity: 1, y: 0 },
  transition: { duration: 0.6, delay, ease: [0.19, 1, 0.22, 1] },
})

const itemVariants = {
  hidden: { opacity: 0, y: 20 },
  show: { opacity: 1, y: 0, transition: { type: 'spring', stiffness: 300, damping: 24 } }
}

export default function CourtFiling() {
  const { disputeId } = useParams()
  const { API_URL } = useAppContext()

  const cards = [
    {
      icon: FileText, title: 'Petition PDF', desc: 'Pre-filled court petition generated by AI',
      color: '#a78bfa', bg: 'rgba(118,75,162,0.1)', border: 'rgba(118,75,162,0.3)',
      link: `${API_URL}/court/${disputeId}/petition`
    },
    {
      icon: Package, title: 'Evidence Bundle', desc: 'Complete ZIP of statements, sessions, and awards',
      color: '#68d391', bg: 'rgba(72,187,120,0.1)', border: 'rgba(72,187,120,0.3)',
      link: `${API_URL}/court/${disputeId}/evidence-bundle`
    },
    {
      icon: ExternalLink, title: 'eCourts Portal', desc: 'File directly on the Govt eCourts portal',
      color: '#f6ad55', bg: 'rgba(237,137,54,0.1)', border: 'rgba(237,137,54,0.3)',
      link: 'https://efiling.ecourts.gov.in/'
    }
  ]

  return (
    <div style={{ maxWidth: 900, margin: '0 auto', padding: '32px 24px' }}>
      <motion.div {...fadeUp()} style={{ textAlign: 'center', marginBottom: 32 }}>
        <h1 style={{ fontSize: '2.2rem', fontWeight: 800, fontFamily: 'Outfit', marginBottom: 6 }}>
          <span className="gradient-text">Court Filing</span>
        </h1>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 6, color: '#64748b', fontSize: '0.85rem' }}>
          <ShieldCheck size={14} style={{ color: '#fc5c65' }} /> Enforcement under CPC 1908 & Arbitration Act 1996
        </div>
      </motion.div>

      <EscalationTracker currentStage="court_filing" />

      <motion.div {...fadeUp(0.1)} className="glass-static" style={{ marginTop: 32, padding: '48px 32px', textAlign: 'center', borderRadius: 24 }}>
        <motion.div animate={{ rotate: [0, 5, -5, 0], scale: [1, 1.05, 1] }} transition={{ duration: 4, repeat: Infinity }}
          style={{ width: 80, height: 80, borderRadius: '50%', background: 'rgba(252,92,101,0.1)', border: '1px solid rgba(252,92,101,0.2)',
                   display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 24px' }}>
          <Scale size={40} style={{ color: '#fc5c65' }} />
        </motion.div>
        
        <h3 style={{ fontSize: '1.6rem', fontWeight: 800, fontFamily: 'Outfit', marginBottom: 12 }}>Court Filing Mode Active</h3>
        <p style={{ color: '#94a3b8', fontSize: '1rem', lineHeight: 1.6, maxWidth: 500, margin: '0 auto 48px' }}>
          AI mediation and arbitration were unable to resolve this dispute. Download the evidence package and file your petition on eCourts.
        </p>

        <motion.div initial="hidden" animate="show" variants={{ show: { transition: { staggerChildren: 0.1 } } }}
          style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: 20 }}>
          {cards.map((c, i) => (
            <motion.a key={i} variants={itemVariants} href={c.link} target="_blank" rel="noreferrer"
              whileHover={{ y: -8, boxShadow: `0 12px 30px ${c.bg}` }} whileTap={{ scale: 0.96 }}
              className="glass" style={{ padding: 32, textAlign: 'center', borderRadius: 20, display: 'block',
                                         textDecoration: 'none', transition: 'box-shadow 0.3s, transform 0.3s' }}>
              <div style={{ width: 56, height: 56, borderRadius: 16, background: c.bg, border: `1px solid ${c.border}`,
                            display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 20px' }}>
                <c.icon size={26} style={{ color: c.color }} />
              </div>
              <h4 style={{ fontWeight: 800, fontFamily: 'Outfit', fontSize: '1.1rem', color: '#edf2f7', marginBottom: 8 }}>{c.title}</h4>
              <p style={{ color: '#64748b', fontSize: '0.85rem', lineHeight: 1.5 }}>{c.desc}</p>
            </motion.a>
          ))}
        </motion.div>
      </motion.div>
    </div>
  )
}
